export const currencyList = [
  ["AUD", "Australia Dollar"],
  ["GBP", "Great Britain Pound"],
  ["EUR", "Euro"],
  ["JPY", "Japan Yen"],
  ["CHF", "Switzerland Franc"],
  ["USD", "USA Dollar"],
  ["AFN", "Afghanistan Afghani"],
  ["ALL", "Albania Lek"],
  ["DZD", "Algeria Dinar"],
  ["AOA", "Angola Kwanza"],
  ["ARS", "Argentina Peso"],
  ["AMD", "Armenia Dram"],
  ["AWG", "Aruba Florin"],
  ["AZN", "Azerbaijan New Manat"],
  ["BSD", "Bahamas Dollar"],
  ["BHD", "Bahrain Dinar"],
  ["BDT", "Bangladesh Taka"],
  ["BBD", "Barbados Dollar"],
  ["BYR", "Belarus Ruble"],
  ["BZD", "Belize Dollar"],
  ["BMD", "Bermuda Dollar"],
  ["BTN", "Bhutan Ngultrum"],
  ["BOB", "Bolivia Boliviano"],
  ["BAM", "Bosnia Mark"],
  ["BWP", "Botswana Pula"],
  ["BRL", "Brazil Real"],
  ["BND", "Brunei Dollar"],
  ["BGN", "Bulgaria Lev"],
  ["BIF", "Burundi Franc"],
  ["XOF", "CFA Franc BCEAO"],
  ["XAF", "CFA Franc BEAC"],
  ["XPF", "CFP Franc"],
  ["KHR", "Cambodia Riel"],
  ["CAD", "Canada Dollar"],
  ["CVE", "Cape Verde Escudo"],
  ["KYD", "Cayman Islands Dollar"],
  ["CLP", "Chili Peso"],
  ["CNY", "China Yuan/Renminbi"],
  ["COP", "Colombia Peso"],
  ["KMF", "Comoros Franc"],
  ["CDF", "Congo Franc"],
  ["CRC", "Costa Rica Colon"],
  ["HRK", "Croatia Kuna"],
  ["CUC", "Cuba Convertible Peso"],
  ["CUP", "Cuba Peso"],
  ["CZK", "Czech Koruna"],
  ["DKK", "Denmark Krone"],
  ["DJF", "Djibouti Franc"],
  ["DOP", "Dominican Republich Peso"],
  ["XCD", "East Caribbean Dollar"],
  ["EGP", "Egypt Pound"],
  ["SVC", "El Salvador Colon"],
  ["ETB", "Ethiopia Birr"],
  ["FKP", "Falkland Islands Pound"],
  ["FJD", "Fiji Dollar"],
  ["GMD", "Gambia Dalasi"],
  ["GEL", "Georgia Lari"],
  ["GHS", "Ghana New Cedi"],
  ["GIP", "Gibraltar Pound"],
  ["GTQ", "Guatemala Quetzal"],
  ["GNF", "Guinea Franc"],
  ["GYD", "Guyana Dollar"],
  ["HTG", "Haiti Gourde"],
  ["HNL", "Honduras Lempira"],
  ["HKD", "Hong Kong Dollar"],
  ["HUF", "Hungary Forint"],
  ["ISK", "Iceland Krona"],
  ["INR", "India Rupee"],
  ["IDR", "Indonesia Rupiah"],
  ["IRR", "Iran Rial"],
  ["IQD", "Iraq Dinar"],
  ["ILS", "Israel New Shekel"],
  ["JMD", "Jamaica Dollar"],
  ["JOD", "Jordan Dinar"],
  ["KZT", "Kazakhstan Tenge"],
  ["KES", "Kenya Shilling"],
  ["KWD", "Kuwait Dinar"],
  ["KGS", "Kyrgyzstan Som"],
  ["LAK", "Laos Kip"],
  ["LBP", "Lebanon Pound"],
  ["LSL", "Lesotho Loti"],
  ["LRD", "Liberia Dollar"],
  ["LYD", "Libya Dinar"],
  ["MOP", "Macau Pataca"],
  ["MKD", "Macedonia Denar"],
  ["MGA", "Malagasy Ariary"],
  ["MWK", "Malawi Kwacha"],
  ["MYR", "Malaysia Ringgit"],
  ["MVR", "Maldives Rufiyaa"],
  ["MRO", "Mauritania Ouguiya"],
  ["MUR", "Mauritius Rupee"],
  ["MXN", "Mexico Peso"],
  ["MDL", "Moldova Leu"],
  ["MNT", "Mongolia Tugrik"],
  ["MAD", "Morocco Dirham"],
  ["MZN", "Mozambique New Metical"],
  ["MMK", "Myanmar Kyat"],
  ["ANG", "NL Antilles Guilder"],
  ["NAD", "Namibia Dollar"],
  ["NPR", "Nepal Rupee"],
  ["NZD", "New Zealand Dollar"],
  ["NIO", "Nicaragua Cordoba Oro"],
  ["NGN", "Nigeria Naira"],
  ["KPW", "North Korea Won"],
  ["NOK", "Norway Kroner"],
  ["OMR", "Oman Rial"],
  ["PKR", "Pakistan Rupee"],
  ["PAB", "Panama Balboa"],
  ["PGK", "Papua New Guinea Kina"],
  ["PYG", "Paraguay Guarani"],
  ["PEN", "Peru Nuevo Sol"],
  ["PHP", "Philippines Peso"],
  ["PLN", "Poland Zloty"],
  ["QAR", "Qatar Rial"],
  ["RON", "Romania New Lei"],
  ["RUB", "Russia Rouble"],
  ["RWF", "Rwanda Franc"],
  ["WST", "Samoa Tala"],
  ["STD", "Sao Tome/Principe Dobra"],
  ["SAR", "Saudi Arabia Riyal"],
  ["RSD", "Serbia Dinar"],
  ["SCR", "Seychelles Rupee"],
  ["SLL", "Sierra Leone Leone"],
  ["SGD", "Singapore Dollar"],
  ["SBD", "Solomon Islands Dollar"],
  ["SOS", "Somali Shilling"],
  ["ZAR", "South Africa Rand"],
  ["KRW", "South Korea Won"],
  ["LKR", "Sri Lanka Rupee"],
  ["SHP", "St Helena Pound"],
  ["SDG", "Sudan Pound"],
  ["SRD", "Suriname Dollar"],
  ["SZL", "Swaziland Lilangeni"],
  ["SEK", "Sweden Krona"],
  ["SYP", "Syria Pound"],
  ["TWD", "Taiwan Dollar"],
  ["TZS", "Tanzania Shilling"],
  ["THB", "Thailand Baht"],
  ["TOP", "Tonga Pa'anga"],
  ["TTD", "Trinidad/Tobago Dollar"],
  ["TND", "Tunisia Dinar"],
  ["TRY", "Turkish New Lira"],
  ["UGX", "Uganda Shilling"],
  ["UAH", "Ukraine Hryvnia"],
  ["UYU", "Uruguay Peso"],
  ["AED", "United Arab Emirates Dirham"],
  ["VUV", "Vanuatu Vatu"],
  ["VND", "Vietnam Dong"],
  ["YER", "Yemen Rial"],
  ["ZMK", "Zambia Kwacha"],
];
